### ISSUE TITLE
Bad Twitter link in GH profile

### ISSUE THREAD

**Issue by webknjaz** [MarcoGorelli/MarcoGorelli#1]
Hi :wave:!

I just noticed that https://twitter.com/marco_gorelli linked from your GitHub profile doesn't exist. FYI.

P.S. Thanks for your `cython-lint` project. Love it! Just integrated into https://github.com/ansible/pylibssh :)

**Comment by MarcoGorelli** [comment]
Hey @webknjaz , thanks for letting me know! Yeah I felt it was time to deactivate my profile, I've removed the link

> Love it! Just integrated into https://github.com/ansible/pylibssh :)

Awesome! More checks coming, please do let me know if you run into issues and/or have ideas for new checks

All the best, take care, Слава Україні

**Comment by webknjaz** [comment]
Thanks! One idea could be sourcing the line length value from `.flake8` and other known locations. Having it in a config file allows invoking the tool via pre-commit or externally without having to remember to copy the args.

**Comment by MarcoGorelli** [comment]
thanks for the suggestion - yeah if the tool becomes more popular I should probably add configuration files
